const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(__dirname + '/app.js', 'utf8');
const functions = source.match(/^function \w+\([^]*?^}/gm).join('\n');
const context = vm.createContext({ console, crypto: require('node:crypto').webcrypto });
vm.runInContext('const LEGACY_PURCHASE_DATE = "2026-09-05";\n' + functions, context);
const holding = { symbol: 'TEST', shares: 10, avgCost: 100, currentPrice: 80, side: 'short' };
assert.equal(context.stockBookValue(holding), 1200);
assert.equal(context.stockBookValue({ ...holding, currentPrice: 120 }), 800);
assert.equal(context.stockBookValue({ ...holding, currentPrice: null }), 1000);
assert.equal(context.stockBookValue({ ...holding, side: 'long' }), 800);
assert.equal(context.stockDisplaySymbol(holding), 'TEST(short)');
assert.equal(context.calculateTradeValues('tw', 10, 100, 80, 1, 'short').pnlTwd, 200);
assert.equal(context.calculateTradeValues('us', 10, 100, 80, 32, 'short').pnlTwd, 6400);
assert.equal(context.calculateTradeValues('us', 10, 100, 120, 32, 'short').pnlPct, -20);
assert.equal(context.calculateTradeValues('tw', 10, 100, 80, 1).pnlTwd, -200);
const trade = context.createTradeRecord({ ...holding, market: 'us', sellPrice: 80, fxRate: 32, buyDate: '2026-09-05', sellDate: '2026-09-14' });
assert.equal(context.tradeDate('2026-9-5'), '2026/09/05');
assert.equal(context.holdingDays(trade), 9);
assert.equal(context.holdingDays({ buyDate: '2024-02-28', sellDate: '2024-03-01' }), 2);
assert.equal(context.holdingDays({ buyDate: '2026/09/21', sellDate: '2026/09/21' }), 0);
const html = context.renderTradeRecord(trade);
assert.equal(context.getTradeDisplayLabel({ market: 'tw', name: '台積電', symbol: '2330' }), '台積電 / 2330');
assert.equal(context.getTradeDisplayLabel({ market: 'us', name: 'Apple', symbol: 'AAPL' }), 'AAPL');
assert.equal(context.getTradeDisplayLabel({ market: 'us', symbol: 'AAPL', side: 'short' }), 'AAPL(short)');
assert.equal(context.getTradeDisplayLabel({ market: 'us', name: 'Apple', symbol: 'AAPL', side: 'short' }), 'AAPL(short)');
assert.ok(html.indexOf('賣出</small>') < html.indexOf('買入</small>'));
assert.ok(html.indexOf('持有天數') < html.indexOf('股名／股號'));
const data = context.migrateState(JSON.parse(JSON.stringify({ holdings: [holding], usHoldings: [holding], history: [], tradeHistory: [trade], usdTwdRate: 32 })));
assert.equal(data.holdings[0].side, 'short');
assert.equal(data.usHoldings[0].side, 'short');
assert.equal(data.tradeHistory[0].side, 'short');
assert.equal(data.tradeHistory[0].pnlTwd, 6400);
assert.equal(context.migrateState({ holdings: [{ ...holding, side: undefined }], history: [] }).holdings[0].side, 'long');
console.log('PASS: short/long P&L, FX, missing price, labels, JSON migration, legacy defaults');
