const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(__dirname + '/app.js', 'utf8');
const functions = source.match(/^function \w+\([^]*?^}/gm).join('\n');
const context = vm.createContext({ console, crypto: require('node:crypto').webcrypto });
vm.runInContext('const LEGACY_PURCHASE_DATE = "2026-09-05";\n' + functions, context);
const holding = { symbol: 'TEST', shares: 10, avgCost: 100, currentPrice: 80, side: 'short' };
assert.equal(context.stockBookValue(holding), 1200);
assert.equal(context.stockBookValue({ ...holding, currentPrice: 120 }), 800);
assert.equal(context.stockBookValue({ ...holding, currentPrice: null }), 1000);
assert.equal(context.stockBookValue({ ...holding, side: 'long' }), 800);
assert.equal(context.stockDisplaySymbol(holding), 'TEST(short)');
assert.equal(context.calculateTradeValues('tw', 10, 100, 80, 1, 'short').pnlTwd, 200);
assert.equal(context.calculateTradeValues('us', 10, 100, 80, 32, 'short').pnlTwd, 6400);
assert.equal(context.calculateTradeValues('us', 10, 100, 120, 32, 'short').pnlPct, -20);
assert.equal(context.calculateTradeValues('tw', 10, 100, 80, 1).pnlTwd, -200);
const trade = context.createTradeRecord({ ...holding, market: 'us', sellPrice: 80, fxRate: 32, buyDate: '2026-09-05', sellDate: '2026-09-14' });
const data = context.migrateState(JSON.parse(JSON.stringify({ holdings: [holding], usHoldings: [holding], history: [], tradeHistory: [trade], usdTwdRate: 32 })));
assert.equal(data.holdings[0].side, 'short');
assert.equal(data.usHoldings[0].side, 'short');
assert.equal(data.tradeHistory[0].side, 'short');
assert.equal(data.tradeHistory[0].pnlTwd, 6400);
assert.equal(context.migrateState({ holdings: [{ ...holding, side: undefined }], history: [] }).holdings[0].side, 'long');
console.log('PASS: short/long P&L, FX, missing price, labels, JSON migration, legacy defaults');
